version: "3"

services:
  mariadb:
    image: mariadb
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: firstdb
      MYSQL_USER: superuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"

  tomcat:
    image: tomcat
    container_name: tomcat_container
    ports:
      - "8080:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps

  # oracle:  
  #   image: container-registry.oracle.com/database/enterprise:19.3.0.0
  #   container_name: oracle_container
  #   environment:
  #     - ORACLE_SID=your_sid
  #     - ORACLE_PDB=your_pdb
  #     - ORACLE_PWD=your_password
  #   volumes:
  #     - ./oracle-data:/opt/oracle/oradata

# networks:
#   default:
#     external:
#       name: bridge
